image: node:latest

stages:
  - build
  - lint

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  tags:
    - java
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Lint JavaScript code using ESLint.
eslint:
  stage: lint
  when: always
  tags:
    - java
  variables:
    CI_PROJECT_DIR: '/builds/Learnweb/Learnweb/'
  script:
    - npm run js:lint -s
#    - npx eslint --format gitlab WebContent/resources/layout/js/**
#  artifacts:
#    reports:
#      codequality: eslint-codequality.json

# Lint SCSS using stylelint.
stylelint:
  stage: lint
  when: always
  tags:
    - java
  script:
    - npm run scss:lint -s
