image: node:latest

variables:
  PROXY_SETTINGS: "-DproxySet=true -Dhttp.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=learnweb.l3s.uni-hannover.de -Dhttps.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=learnweb.l3s.uni-hannover.de"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository $PROXY_SETTINGS"

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - node_modules/

# Check for code style issues
lint:
  stage: lint
  tags:
    - javascript
  script:
    - npm install --no-audit
    - npm run lint -s

# Run Java tests (only if `lint` is passed)
test:
  stage: test
  tags:
    - java
  script:
    - mvn test -Dexec.skip --batch-mode

# Any commit to `master` branch will be deployed to /dev instance (only if `lint` and `test` have passed)
deploy:
  stage: deploy
  tags:
    - java
  script:
    - mvn tomcat7:redeploy -DskipTests -P dev,!local --batch-mode
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

# A commit to `master` brunch with message `chore: version release` will be deployed to ROOT instance
deployProd:
  stage: deploy
  tags:
    - java
  script:
    - mvn tomcat7:redeploy -DskipTests -P prod,!local --batch-mode
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE == "chore: version release"'
      when: on_success
