variables:
  MAVEN_OPTS: "-DproxySet=true -Dhttp.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=learnweb.l3s.uni-hannover.de -Dhttps.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=learnweb.l3s.uni-hannover.de"
  MAVEN_CLI_OPTS: "-P prod,!local --batch-mode"
  MAVEN_CLI_QUIET: "--quiet -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.MavenCli=OFF"

stages:
  - lint
  - test
  - build
  - deploy

# Check for code style issues
lint:
  stage: lint
  tags:
    - javascript
    - java
  script:
    - npm ci
    - npm run lint --silent
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_QUIET checkstyle:check
  cache:
    paths:
      - node_modules/

# Run Java tests
test:
  stage: test
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_QUIET compile spotbugs:check
    - mvn $MAVEN_CLI_OPTS test
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'

# Build Java sources (includes tests)
build:
  stage: build
  tags:
    - javascript
    - java
  script:
    - npm run build
    - mvn $MAVEN_CLI_OPTS $MAVEN_CLI_QUIET spotbugs:check
    - mvn $MAVEN_CLI_OPTS install
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  cache:
    paths:
      - node_modules/
      - target/Learnweb.war

# Any commit to `master` branch will be deployed to /dev instance
deploy_dev:
  stage: deploy
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS tomcat7:redeploy-only -Dpath=dev
  environment:
    name: dev
    url: https://learnweb.l3s.uni-hannover.de/dev/
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  cache:
    paths:
      - target/Learnweb.war
    policy: pull

# A commit to `master` brunch with message `chore: version release` will be deployed to ROOT instance
deploy_prod:
  stage: deploy
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS tomcat7:deploy-only -Dpath=ROOT
  environment:
    name: prod
    url: https://learnweb.l3s.uni-hannover.de/
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE == "chore: version release"'
  cache:
    paths:
      - target/Learnweb.war
    policy: pull
