variables:
  MAVEN_OPTS: "-DproxySet=true -Dhttp.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=learnweb.l3s.uni-hannover.de -Dhttps.proxyHost=web-proxy.rrzn.uni-hannover.de -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=learnweb.l3s.uni-hannover.de"
  MAVEN_CLI_OPTS: "-P prod,!local --batch-mode"

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - target/Learnweb.war

# Check for code style issues
lint:
  stage: lint
  tags:
    - javascript
  script:
    - npm install --no-audit
    - npm run lint -s

# Run Java tests (only if `lint` is passed)
test:
  stage: test
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS test

# Build Java sources (only if `test` is passed)
build:
  stage: deploy
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS install -DskipTests
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

# Any commit to `master` branch will be deployed to /dev instance
deploy_dev:
  stage: deploy
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS tomcat7:redeploy-only -Dpath=dev
  environment:
    name: dev
    url: https://learnweb.l3s.uni-hannover.de/dev/
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success

# A commit to `master` brunch with message `chore: version release` will be deployed to v3 (later ROOT) instance
deploy_prod:
  stage: deploy
  tags:
    - java
  script:
    - mvn $MAVEN_CLI_OPTS tomcat7:deploy-only -Dpath=v3
  environment:
    name: prod
    url: https://learnweb.l3s.uni-hannover.de/
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE == "chore: version release"'
      when: on_success
