image: node:latest

stages:
  - build
  - lint

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Lint JavaScript code using ESLint.
eslint:
  stage: lint
  when: always
  variables:
    CI_PROJECT_DIR: '/builds/Learnweb/Learnweb/'
  script:
    - npx eslint --format gitlab WebContent/resources/learnweb-layout/js/**
  artifacts:
    reports:
      codequality: eslint-codequality.json

# Lint SCSS using stylelint.
stylelint:
  stage: lint
  when: always
  script:
    - npm run scss:lint -s
