services:
  webapp:
    image: tomcat:10.1-jdk17
    restart: always
    volumes:
      - "./target/Learnweb.war:/usr/local/tomcat/webapps/ROOT.war"
      - "./data/files:/mnt/files"
    ports:
      - "7010:8080"
    depends_on:
      - mariadb
      - solr
    environment:
      TZ: "Europe/Berlin"
      LEARNWEB_FILE_MANAGER_FOLDER: "/mnt/files"
      LEARNWEB_SOLR_SERVER_URL: "http://solr:8983/solr/learnweb"
      LEARNWEB_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/learnweb"
      LEARNWEB_DATASOURCE_USERNAME: "learnweb"
      LEARNWEB_DATASOURCE_PASSWORD: "cm&dY@FSM7sCtSxZ"
  mariadb:
    image: mariadb:10.11
    restart: always
    ports:
      - "7006:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
    environment:
      TZ: "Europe/Berlin"
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "learnweb"
      MARIADB_USER: "learnweb"
      MARIADB_PASSWORD: "cm&dY@FSM7sCtSxZ"
  solr:
    image: solr:9
    restart: always
    ports:
      - "7003:8983"
    volumes:
      - "./src/main/conf/solr-setup.sh:/solr-setup.sh:ro"
      - "./data/solr:/var/solr"
    command: bash -e -c "precreate-core learnweb && source /solr-setup.sh && solr-foreground"
  fuseki:
    image: secoresearch/fuseki:latest
    restart: always
    environment:
      ADMIN_PASSWORD: "oydyoMQSP7^R%X"
    ports:
      - "7005:3030"
    volumes:
      - "./data/fuseki/db:/fuseki-base/databases"
      - "./data/fuseki/conf:/fuseki-base/configuration"
    command: bash -e -c "precreate-core learnweb && source /solr-setup.sh && solr-foreground"
