services:
  webapp:
    image: tomcat:11
    restart: unless-stopped
    volumes:
      # the project has to be built (mvn clean package -Pprod) before running the docker-compose
      - "./target/Learnweb.war:/usr/local/tomcat/webapps/ROOT.war"
      - "./data/files:/mnt/files"
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - solr
    environment:
      TZ: "Europe/Berlin"
      LEARNWEB_FILE_MANAGER_FOLDER: "/mnt/files"
      LEARNWEB_SOLR_SERVER_URL: "http://solr:8983/solr/learnweb"
      LEARNWEB_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/${MARIADB_DATABASE}"
      LEARNWEB_DATASOURCE_USERNAME: "${MARIADB_USER}"
      LEARNWEB_DATASOURCE_PASSWORD: "${MARIADB_PASSWORD}"

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
    environment:
      TZ: "Europe/Berlin"
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"

  solr:
    image: solr:9
    restart: unless-stopped
    ports:
      - "8983:8983"
    environment:
      - SOLR_MODULES=extraction
    volumes:
      - "./src/main/conf/solr-setup.sh:/solr-setup.sh:ro"
      - "./data/solr:/var/solr"
    command: bash -e -c "precreate-core learnweb && source /solr-setup.sh && solr-foreground"
