// Generated by DB Solo 4.3 on 23.08.2014 at 14:58:58
package de.l3s.archivedemo;

public class DAOException extends Exception
{
    public DAOException(String s, Exception e)
    {
	super(s, e);
    }

    public DAOException(String e)
    {
	super(e);
    }

    public DAOException(Exception e)
    {
	super(e);
    }
}
