// Generated by DB Solo 4.3 on 23.08.2014 at 14:58:58
package de.l3s.archivedemo;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

public class Query
{
    //  private final static Logger log = Logger.getLogger(Query.class);

    private int queryId;
    private int estimatedResultCount = -2;
    private int loadedResultCount = -2;
    private int requestedResultCount;
    private Date timestamp = new Date();
    private String type;
    private String market;
    private String queryString;
    private boolean disableQueryAlterations = false;

    //cached values:
    private List<Result> results;

    public Query()
    {
	this.type = "web";
    }

    public void addResult(Result result)
    {
	if(null == results)
	    results = new LinkedList<Result>();

	results.add(result);
    }

    public List<Result> getResults() throws DAOException
    {
	if(null == results)
	    results = DAOFactory.getResultDAO().getByQueryId(queryId, getRequestedResultCount());
	return results;
    }

    /**
     * 
     * @return is true if the results of this query were loaded before
     */
    public boolean isCached()
    {
	if(getTimestamp() == null)
	    return false;

	return true;
    }

    public int getRequestCount()
    {
	if(loadedResultCount < 0)
	    return 0;
	if(loadedResultCount == 0)
	    return 1;
	return (int) Math.ceil(loadedResultCount / 50.0);
    }

    //
    // getters / setters
    //

    public int getQueryId()
    {
	return this.queryId;
    }

    public void setResults(List<Result> results)
    {
	this.results = results;
    }

    public String getQueryString()
    {
	return queryString;
    }

    public void setQueryString(String queryString)
    {
	this.queryString = queryString;
    }

    public void setQueryId(int queryId)
    {
	this.queryId = queryId;
    }

    public int getRequestedResultCount()
    {
	return requestedResultCount;
    }

    public void setRequestedResultCount(int requestedResultCount)
    {
	this.requestedResultCount = requestedResultCount;
    }

    public int getEstimatedResultCount()
    {
	return this.estimatedResultCount;
    }

    public void setEstimatedResultCount(int results)
    {
	this.estimatedResultCount = results;
    }

    public int getLoadedResultCount()
    {
	return this.loadedResultCount;
    }

    public void setLoadedResultCount(int loadedResults)
    {
	this.loadedResultCount = loadedResults;
    }

    public Date getTimestamp()
    {
	return this.timestamp;
    }

    public void setTimestamp(Date timestamp)
    {
	this.timestamp = timestamp;
    }

    public String getType()
    {
	return this.type;
    }

    public void setType(String type)
    {
	this.type = type;
    }

    public String getMarket()
    {
	return market;
    }

    public void setMarket(String market)
    {
	this.market = market;
    }

    public boolean isDisableQueryAlterations()
    {
	return disableQueryAlterations;
    }

    public void setDisableQueryAlterations(boolean disableQueryAlterations)
    {
	this.disableQueryAlterations = disableQueryAlterations;
    }

}
