// Generated by DB Solo 4.3 on 23.08.2014 at 14:58:58
package de.l3s.archivedemo;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;

import de.l3s.learnweb.Learnweb;
import de.l3s.learnweb.ResourceDecorator;

public class Query
{
    //  private final static Logger log = Logger.getLogger(Query.class);

    private int id = -1;
    private int estimatedResultCount = -2;
    private int loadedResultCount = -2;
    private int requestedResultCount;
    private Date timestamp = new Date();
    private String market;
    private String queryString;
    private boolean disableQueryAlterations = false;

    //cached values:
    private transient List<ResourceDecorator> results;

    public Query()
    {
    }

    public List<ResourceDecorator> getResults() throws SQLException
    {
	if(null == results)
	    results = Learnweb.getInstance().getArchiveSearchManager().getResultsByQueryId(id);
	return results;
    }

    public void setResults(List<ResourceDecorator> results)
    {
	this.results = results;
    }

    /**
     * 
     * @return is true if the results of this query were loaded before
     */

    //
    // getters / setters
    //

    public String getQueryString()
    {
	return queryString;
    }

    public void setQueryString(String queryString)
    {
	this.queryString = queryString;
    }

    public int getRequestedResultCount()
    {
	return requestedResultCount;
    }

    public void setRequestedResultCount(int requestedResultCount)
    {
	this.requestedResultCount = requestedResultCount;
    }

    public int getEstimatedResultCount()
    {
	return this.estimatedResultCount;
    }

    public void setEstimatedResultCount(int results)
    {
	this.estimatedResultCount = results;
    }

    public int getLoadedResultCount()
    {
	return this.loadedResultCount;
    }

    public void setLoadedResultCount(int loadedResults)
    {
	this.loadedResultCount = loadedResults;
    }

    public Date getTimestamp()
    {
	return this.timestamp;
    }

    public void setTimestamp(Date timestamp)
    {
	this.timestamp = timestamp;
    }

    public String getMarket()
    {
	return market;
    }

    public void setMarket(String market)
    {
	this.market = market;
    }

    public boolean isDisableQueryAlterations()
    {
	return disableQueryAlterations;
    }

    public void setDisableQueryAlterations(boolean disableQueryAlterations)
    {
	this.disableQueryAlterations = disableQueryAlterations;
    }

    public int getId()
    {
	return id;
    }

    public void setId(int id)
    {
	this.id = id;
    }

}
