ALTER TABLE `lw_survey_question`
    MODIFY `question_type` ENUM ('INPUT_TEXT','INPUT_TEXTAREA','ONE_BUTTON','ONE_RADIO','ONE_MENU','ONE_MENU_EDITABLE','MANY_CHECKBOX','MULTIPLE_MENU','FULLWIDTH_HEADER') NOT NULL;
