ALTER TABLE `lw_group` ADD `image_file_id` INT(10) UNSIGNED DEFAULT NULL AFTER `description`;

ALTER TABLE `lw_group` ADD CONSTRAINT `fk_lw_group_lw_file` FOREIGN KEY (`image_file_id`) REFERENCES `lw_file` (`file_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `lw_file` MODIFY
    `type` ENUM ('SYSTEM_FILE','ORGANISATION_BANNER','PROFILE_PICTURE','GROUP_PICTURE','THUMBNAIL_SMALL','THUMBNAIL_MEDIUM','THUMBNAIL_LARGE','MAIN','ORIGINAL','GLOSSARY','DOC_HISTORY','DOC_CHANGES') NOT NULL;
