name: test

on:
  push:
    branches:
      - main

env:
  MVN: mvn --show-version --batch-mode --quiet
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:scss --silent
      - run: npm run lint:js --silent

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github-l3s-learnweb
      - run: $MVN checkstyle:check
      - run: $MVN compile spotbugs:check

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github-l3s-learnweb
      - run: $MVN test
