name: CI

on:
  push:
    branches:
  pull_request:

env:
  MVN: mvn --batch-mode

jobs:
  lint-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint:scss --silent
      - run: npm run lint:js --silent

  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: CheckStyle
        run: $MVN checkstyle:check

      - name: SpotBugs
        if: success() || failure()
        run: $MVN compile spotbugs:check

  tests-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: $MVN --show-version test
