name: Deploy Prod

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - id: get_version
        name: Get version
        uses: astappiev/get-version-from-tag@v1
        with:
          format: 'tomcat'

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - run: mvn --batch-mode -P prod,!local -Drevision=${{ steps.get_version.outputs.version }} install

      - uses: actions/upload-artifact@v4
        with:
          name: learnweb-release
          path: target/Learnweb.war
          if-no-files-found: error

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          proxy_host: ${{ secrets.DEPLOY_JUMP_HOST }}
          proxy_username: ${{ secrets.DEPLOY_JUMP_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          script: |
            #!/bin/bash
            set -e

            cd ~/stacks/learnweb/webapps
            TEMP_DIR=$(mktemp -d)

            echo "Getting artifact from workflow ${{ github.run_id }}"
            ARTIFACT_ID=$(curl -s \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" | \
              jq -r '.artifacts[] | select(.name=="learnweb-release") | .id')

            echo "Downloading artifact $ARTIFACT_ID"
            curl -L -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip" \
              -o "${TEMP_DIR}/artifact.zip"

            unzip -q "${TEMP_DIR}/artifact.zip" -d "${TEMP_DIR}"
            mv "${TEMP_DIR}/Learnweb.war" "ROOT##${{ needs.build-release.outputs.version }}.war"
            echo "Artifact deployed"
            rm -rf "${TEMP_DIR}"
