name: Deploy Dev

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - run: mvn --batch-mode -P prod,!local -Dmaven.test.skip=true -Drevision=dev-${{ github.sha }} install

      - uses: actions/upload-artifact@v4
        with:
          name: learnweb-war
          path: target/Learnweb.war
          if-no-files-found: error

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          proxy_host: ${{ secrets.DEPLOY_JUMP_HOST }}
          proxy_username: ${{ secrets.DEPLOY_JUMP_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          script: |
            #!/bin/bash
            set -e

            cd ~/stacks/learnweb_dev/webapps
            TEMP_DIR=$(mktemp -d)

            echo "Getting artifact from workflow ${{ github.run_id }}"
            ARTIFACT_ID=$(curl -s \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" | \
              jq -r '.artifacts[] | select(.name=="learnweb-war") | .id')

            echo "Downloading artifact $ARTIFACT_ID"
            curl -L -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip" \
              -o "${TEMP_DIR}/artifact.zip"

            unzip -q "${TEMP_DIR}/artifact.zip" -d "${TEMP_DIR}"
            mv "${TEMP_DIR}/Learnweb.war" "ROOT##dev.war"
            echo "Artifact deployed"
            rm -rf "${TEMP_DIR}"
